create table PUBLIC.BASKET (
    ID BIGINT AUTO_INCREMENT,
    PRODUCT_AT TIMESTAMP,
    PRIMARY KEY (ID)
);

create table PUBLIC.FRUIT (
    ID BIGINT auto_increment,
    HARVEST_At TIMESTAMP,
    BASKET_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (BASKET_ID) REFERENCES PUBLIC.BASKET(ID)
)